# Generated by Django 4.0.1 on 2022-05-20 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.IntegerField()),
                ('entry_id', models.IntegerField()),
                ('field1', models.FloatField(null=True)),
                ('field2', models.FloatField(null=True)),
                ('field3', models.FloatField(null=True)),
                ('field4', models.FloatField(null=True)),
                ('field5', models.FloatField(null=True)),
                ('field6', models.FloatField(null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user_id', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('description', models.TextField(default='')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
